// ===================================
// Main.cpp file generated by OptFrame
// Project TP
// ===================================
extern int PRINTING_LEVEL = 2;
#include <stdlib.h>
#include <math.h>
#include <iostream>

// LOADER IS NOT DEFAULT ANYMORE. USE ONLY IF YOU NEED...
//#include "../OptFrame/Loader.hpp"

#include "TP.h"

#include "./TP/Representation.h"
#include "./TP/Solution.h"
#include "./TP/Evaluation.h"
#include "./TP/Evaluator.h"

using namespace std;
using namespace optframe;
using namespace TP;

int main(int argc, char **argv)
{
	RandGen rg;
	long seed = time(NULL);
	seed = 10;
	cout << "Seed = " << seed << endl;
	rg.setSeed(seed);

	cout << "creating problem instance" << endl;
	ProblemInstance p;
	cout << "problem instance ok " << endl;

	int nodeMaxChildren = 5;
	int treeMaxDepth = 3;
	ConstructiveRandom c(p, rg, nodeMaxChildren, treeMaxDepth);

	SolutionTP sol = c.generateSolution();
	cout << "solucao gerada com sucesso!" << endl;
	TPEvaluator eval(p);
	cout << eval.evaluate(sol.getR()).evaluation();

	// Initialize here all your OptFrame components
	// (ProblemInstance, Evaluator, Constructive, ...)

	cout << "PROGRAMM ended successfully" << endl;

	return 0;
}
