// ===================================
// Main.cpp file generated by OptFrame
// Project TP
// ===================================

#include <stdlib.h>
#include <math.h>
#include <iostream>

// LOADER IS NOT DEFAULT ANYMORE. USE ONLY IF YOU NEED...
//#include "../OptFrame/Loader.hpp"

#include "TP.h"

#include "./TP/Representation.h"
#include "./TP/Solution.h"
#include "./TP/Evaluation.h"
#include "./TP/Evaluator.h"

using namespace std;
using namespace optframe;
using namespace TP;

int main(int argc, char **argv)
{
	RandGen rg;
	long seed = time(NULL);
	seed = 10;
	cout << "Seed = " << seed << endl;
	rg.setSeed(seed);

	ProblemInstance p;
	ConstructiveRandom c(p, rg);
	SolutionTP sol = c.generateSolution();

	TPEvaluator eval(p);
	cout<<eval.evaluate(sol.getR()).evaluation();

	// Initialize here all your OptFrame components
	// (ProblemInstance, Evaluator, Constructive, ...)

	cout << "PROGRAMM ended successfully" << endl;

	return 0;
}
